
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Umayanga Avi
 */
public class Home_Activity extends javax.swing.JFrame {

    /**
     * Creates new form Home_Activity
     */
    
    
    int pos = 0;
    
    public Home_Activity() {
        initComponents();
        Show_Product_In_Table();
        Show_Product_In_Table2();
       // combo();
        this.setLocationRelativeTo(null);
       
        //account_name.setText("Username is : " + Login_Activity.useriname_txt.getText());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        account_name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        nic_txt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        address_txt = new javax.swing.JTextArea();
        contact_no_txt = new javax.swing.JTextField();
        insert_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        pre_btn = new javax.swing.JButton();
        next_btn = new javax.swing.JButton();
        bill_cal_btn = new javax.swing.JButton();
        bill_create_txt1 = new javax.swing.JTextField();
        Month_Bill = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        month_select_cmbo = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Meeter");

        account_name.setText("jLabel1");

        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "NIC NO", "Address", "Contact_No", "Pre_Monthly Bill", "This_Month_Bill"
            }
        ));
        detailsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(detailsTable);

        jLabel2.setText("Name");

        jLabel3.setText("NIC No");

        jLabel4.setText("Address");

        jLabel5.setText("Contact No");

        address_txt.setColumns(20);
        address_txt.setRows(5);
        jScrollPane2.setViewportView(address_txt);

        insert_btn.setText("Insert");
        insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btnActionPerformed(evt);
            }
        });

        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        pre_btn.setText("<<");
        pre_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pre_btnActionPerformed(evt);
            }
        });

        next_btn.setText(">>");
        next_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_btnActionPerformed(evt);
            }
        });

        bill_cal_btn.setText("Create Bill");
        bill_cal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bill_cal_btnActionPerformed(evt);
            }
        });

        Month_Bill.setText("Pre Month Bill");

        jLabel6.setText("Enter Point");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cu_ID", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        month_select_cmbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(account_name, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(contact_no_txt)
                            .addComponent(nic_txt)
                            .addComponent(name_txt)))
                    .addComponent(bill_cal_btn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pre_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(next_btn))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(insert_btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(update_btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(delete_btn))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Month_Bill)
                                .addComponent(jLabel6))
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bill_create_txt1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(month_select_cmbo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(account_name)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nic_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(contact_no_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(insert_btn)
                            .addComponent(delete_btn)
                            .addComponent(update_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pre_btn)
                            .addComponent(next_btn))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Month_Bill)
                            .addComponent(month_select_cmbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bill_create_txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bill_cal_btn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(898, 523));
    }// </editor-fold>//GEN-END:initComponents

    private void insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btnActionPerformed
        
        PreparedStatement ps,ps2;
        
        String name = name_txt.getText();
        String nic = nic_txt.getText();
        String address = address_txt.getText();
        String contact = contact_no_txt.getText();
        
        
        String query = "INSERT INTO `main`(`name`, `nic`, `address`, `contact`) VALUES (?,?,?,?)";
        //String query2 ="INSERT INTO `bill`(`cus_id`, `one`, `two`, `three`, `fou`, `fiv`, `six`, `seve`, `eigh`, `nine`, `ten`, `el`, `twel`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try {
            ps = My_Connection.getConnection().prepareStatement(query);
            //ps2 = My_Connection.getConnection().prepareStatement(query2);
            
            ps.setString(1, name);
            ps.setString(2, nic);
            ps.setString(3, address);
            ps.setString(4, contact);
            
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Inserted Data...");
            Show_Product_In_Table();
            
        } catch (SQLException ex) {
            Logger.getLogger(Home_Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_insert_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        
        PreparedStatement ps;
        
        String update = "UPDATE `main` SET `name`=?,`nic`=?,`address`=?,`contact`=? WHERE `name`=? OR `nic`=?";
        
        String name = name_txt.getText();
        String nic = nic_txt.getText();
        String address = address_txt.getText();
        String contact = contact_no_txt.getText();
        
        try {
            ps = My_Connection.getConnection().prepareStatement(update);
            ps.setString(1, name);
            ps.setString(2, nic);
            ps.setString(3, address);
            ps.setString(4, contact);
            
            //where
            ps.setString(5, name);
            ps.setString(6, nic);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Updated Data...");
            Show_Product_In_Table();
            
        } catch (SQLException ex) {
            Logger.getLogger(Home_Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_update_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        
        PreparedStatement ps;
        
        String delete ="DELETE FROM `main` WHERE `nic`=?";
        String nic = nic_txt.getText();
        try {
            ps = My_Connection.getConnection().prepareStatement(delete);
            ps.setString(1, nic);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Deleted Data...");
            Show_Product_In_Table();
        } catch (SQLException ex) {
            Logger.getLogger(Home_Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_delete_btnActionPerformed

    private void next_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_btnActionPerformed

        ResultSet rs ;
        Connection con = null;
        Statement st; 
        
        try {
            
            con = My_Connection.getConnection();
            con.setAutoCommit(false);
            st=con.createStatement();
            String sql1 = "SELECT * FROM `main`";
            st.executeQuery(sql1);
            rs = st.getResultSet();
            
            
              pos = pos+1;
              if(rs.relative(pos))
                {
                    
                    name_txt.setText(rs.getString("name"));
                    nic_txt.setText(rs.getString("nic"));
                    address_txt.setText(rs.getString("address"));
                    contact_no_txt.setText(rs.getString("contact"));
                    //bill_txt.setText(rs.getString("pre_month"));
                   
                }
                else
                {
                    rs.previous();
                    JOptionPane.showMessageDialog(null, "No more records");
                    next_btn.setEnabled(false);
                }
   
            
        } catch (SQLException ex) {
            Logger.getLogger(Home_Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_next_btnActionPerformed

    
    
    private void pre_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pre_btnActionPerformed
        ResultSet rs;
        Connection con = null;
        Statement st;
        
        if (pos>0) {
            try {
            
            con = My_Connection.getConnection();
            con.setAutoCommit(false);
            st=con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String sql1 = "SELECT * FROM `main`";
            rs = st.executeQuery(sql1);
            
            
            pos=pos-1;
            if(rs.relative(pos))
                {
                    next_btn.setEnabled(true);
                    name_txt.setText(rs.getString("name"));
                    nic_txt.setText(rs.getString("nic"));
                    address_txt.setText(rs.getString("address"));
                    contact_no_txt.setText(rs.getString("contact"));
                    //bill_txt.setText(rs.getString("pre_month"));
                    
                }
                else
                {
                    rs.next();
                    JOptionPane.showMessageDialog(null, "No more records");
                    
                }

 
        } catch (SQLException ex) {
            Logger.getLogger(Home_Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else{
            
            JOptionPane.showMessageDialog(null, "No more records");
            
        }
        
        
    }//GEN-LAST:event_pre_btnActionPerformed

    private void bill_cal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bill_cal_btnActionPerformed
    
  String que = "UPDATE `bill` SET `one`=?,`two`=?,`three`=?,`fou`=?,`fiv`=?,`six`=?,`seve`=?,`eigh`=?,`nine`=?,`ten`=?,`el`=?,`twel`=? WHERE `cus_id`=?";
        
  String quee ="UPDATE `bill` SET `one`=? WHERE `cus_id`=?";
  PreparedStatement ps;
  
        String name = name_txt.getText();
        String bill = bill_create_txt1.getText();
        
        if (month_select_cmbo.getSelectedItem().equals("1")) {
            
            try {
            ps = My_Connection.getConnection().prepareStatement(quee);
            ps.setString(1, bill);
            
            
            //where
            ps.setString(2, name);
            
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Updated Data...");
            Show_Product_In_Table();
            
        } catch (SQLException ex) {
            Logger.getLogger(Home_Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
           
        
        
    }//GEN-LAST:event_bill_cal_btnActionPerformed

    private void detailsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailsTableMouseClicked
            
        getSum();            
        
        
        /*name_txt.setText((String) detailsTable.getValueAt(raw,1));
        nic_txt.setText((String) detailsTable.getValueAt(raw, 2));
        address_txt.setText((String) detailsTable.getValueAt(raw, 3));
        contact_no_txt.setText((String) detailsTable.getValueAt(raw, 4));
        */
        
        
    }//GEN-LAST:event_detailsTableMouseClicked

    public void getSum(){
        
        int colmn = detailsTable.getSelectedColumn();
        int rawcount = detailsTable.getRowCount();
        int sum = 0;
        
        for (int i = 0; i< rawcount; i++) {
            
            sum = sum + Integer.parseInt((String) detailsTable.getValueAt(i, 2));
            
        }
        bill_create_txt1.setText(String.valueOf(sum));
        
    }
    
  /*  public void combo(){
        
         ResultSet rs;
        Connection con;
        Statement st;
        
        con = My_Connection.getConnection();
        try {
            st = con.createStatement();
            String query = "SELECT `id` FROM `main`";
            rs = st.executeQuery(query);
            
            while (rs.next()) {                
                jComboBox1.addItem(rs.getString(1));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Home_Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    */
    public void Show_Product_In_Table(){
        
        
       String sql = "SELECT * FROM main";
        try {
            PreparedStatement ps = My_Connection.getConnection().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            detailsTable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            Logger.getLogger(Home_Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void Show_Product_In_Table2(){
        
        
       String sql = "SELECT * FROM bill";
        try {
            PreparedStatement ps = My_Connection.getConnection().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            jTable3.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException ex) {
            Logger.getLogger(Home_Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Month_Bill;
    public javax.swing.JLabel account_name;
    private javax.swing.JTextArea address_txt;
    private javax.swing.JButton bill_cal_btn;
    private javax.swing.JTextField bill_create_txt1;
    private javax.swing.JTextField contact_no_txt;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTable detailsTable;
    private javax.swing.JButton insert_btn;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JComboBox month_select_cmbo;
    private javax.swing.JTextField name_txt;
    private javax.swing.JButton next_btn;
    private javax.swing.JTextField nic_txt;
    private javax.swing.JButton pre_btn;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
