
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Umayanga Avi
 */
public class Register_Activity extends javax.swing.JFrame {

    /**
     * Creates new form Register_Activity
     */
    
    String image_path = null;
    
    public Register_Activity() {
        initComponents();
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(male_opt_btn);
        bg.add(female_opt_btn);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fname_txt = new javax.swing.JTextField();
        lname_txt = new javax.swing.JTextField();
        uname_txt = new javax.swing.JTextField();
        pass_txt = new javax.swing.JPasswordField();
        confpass_txt = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        adress_txt = new javax.swing.JTextArea();
        phone_txt = new javax.swing.JTextField();
        image_path_lbl = new javax.swing.JLabel();
        register_btn = new javax.swing.JButton();
        sentToLogin_btn = new javax.swing.JLabel();
        imageSelect_btn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        male_opt_btn = new javax.swing.JRadioButton();
        female_opt_btn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Register");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("User Name");

        jLabel5.setText("Password");

        jLabel6.setText("Conf Password");

        jLabel7.setText("Address");

        jLabel8.setText("Phone");

        jLabel9.setText("Image");

        pass_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_txtActionPerformed(evt);
            }
        });
        pass_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pass_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pass_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pass_txtKeyTyped(evt);
            }
        });

        adress_txt.setColumns(20);
        adress_txt.setRows(5);
        jScrollPane1.setViewportView(adress_txt);

        phone_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phone_txtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phone_txtKeyTyped(evt);
            }
        });

        image_path_lbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        image_path_lbl.setText("Path of Image");
        image_path_lbl.setFocusable(false);
        image_path_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        register_btn.setText("Register");
        register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_btnActionPerformed(evt);
            }
        });

        sentToLogin_btn.setForeground(new java.awt.Color(51, 51, 255));
        sentToLogin_btn.setText("i have a account...");
        sentToLogin_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sentToLogin_btnMouseClicked(evt);
            }
        });

        imageSelect_btn.setText("Select Image");
        imageSelect_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageSelect_btnActionPerformed(evt);
            }
        });

        jLabel10.setText("Gender");

        male_opt_btn.setText("Male");

        female_opt_btn.setText("Female");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(sentToLogin_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(register_btn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(image_path_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(imageSelect_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fname_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(lname_txt)
                                    .addComponent(uname_txt)
                                    .addComponent(pass_txt)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(phone_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(male_opt_btn)
                                        .addGap(18, 18, 18)
                                        .addComponent(female_opt_btn))
                                    .addComponent(confpass_txt)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(uname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(confpass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(male_opt_btn)
                        .addComponent(female_opt_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(phone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(imageSelect_btn)
                    .addComponent(image_path_lbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sentToLogin_btn)
                    .addComponent(register_btn))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_btnActionPerformed
        
        
        PreparedStatement ps;
        
        String fname = fname_txt.getText();
        String lname = lname_txt.getText();
        String uname = uname_txt.getText();
        String pass = String.valueOf(pass_txt.getPassword());
        String confPass = String.valueOf(confpass_txt.getPassword());
        String address = adress_txt.getText();
        String phone = phone_txt.getText();
        String gender;
        
        if (male_opt_btn.isSelected()) {
            gender="Male";
        }else if(female_opt_btn.isSelected()){
            gender="Female";
        }else{
            gender = "No Selected";
        }       
        
        String querry = "INSERT INTO `login_register`(`fname`, `lname`, `uname`, `pass`, `confpass`, `address`, `phone`,`image`,`gender`) VALUES (?,?,?,?,?,?,?,?,?)";
        
        try {
            ps = My_Connection.getConnection().prepareStatement(querry);
            
            ps.setString(1, fname);
            ps.setString(2, lname);
            ps.setString(3, uname);
            ps.setString(4, pass);
            ps.setString(5, confPass);
            ps.setString(6, address);
            ps.setString(7, phone);
            ps.setString(9, gender);
            
            try {
                
                InputStream image = new FileInputStream(image_path);
                ps.setBlob(8, image);
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Register_Activity.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Inserted Data...");
            
        } catch (SQLException ex) {
            Logger.getLogger(Register_Activity.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_register_btnActionPerformed

    private void imageSelect_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageSelect_btnActionPerformed
       
        String path = null;
        JFileChooser choser = new JFileChooser();
        choser.setCurrentDirectory(new File (System.getProperty("user.home")));
        
        //file extention
        
        FileNameExtensionFilter fileNameExtensionFilter = new FileNameExtensionFilter("*Images", ".jpg",".png",".jpeg");
        choser.addChoosableFileFilter(fileNameExtensionFilter);
        
        int filestate = choser.showSaveDialog(null);
        
        //check if the user select an image
        if (filestate == JFileChooser.APPROVE_OPTION) {
            File selectedImage = choser.getSelectedFile();
            path = selectedImage.getAbsolutePath();
            image_path_lbl.setText(path);
            image_path = path;
        }
        
    }//GEN-LAST:event_imageSelect_btnActionPerformed

    private void phone_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_txtKeyTyped
            
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
        
    }//GEN-LAST:event_phone_txtKeyTyped

    private void phone_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_txtKeyPressed
        
        /*
        char a = evt.getKeyChar();
        if (Character.isLetter(a)) {
            phone_txt.setEditable(false);
        }else{
        phone_txt.setEditable(true);
        }
        */
        
    }//GEN-LAST:event_phone_txtKeyPressed

    private void pass_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_txtActionPerformed
       
    }//GEN-LAST:event_pass_txtActionPerformed

    private void pass_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_txtKeyTyped
       
        String a = String.valueOf(pass_txt.getPassword());
        int as=0;
        if (a.length()>7){
            
            JOptionPane.showMessageDialog(null, "Password is long...Please check password...");
            for (int i = 0; i < a.length(); i++) { 
                
                if (Character.isLetter(a.charAt(i))) {
                    
                   as++; 
                   
                }            
                
            }
            if (as>2) {
                            JOptionPane.showMessageDialog(null, "Password is not match...Please check password...");
                        }
        }

    }//GEN-LAST:event_pass_txtKeyTyped

    private void pass_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_txtKeyPressed
        
    }//GEN-LAST:event_pass_txtKeyPressed

    private void pass_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pass_txtKeyReleased
       
       
    }//GEN-LAST:event_pass_txtKeyReleased

    private void sentToLogin_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sentToLogin_btnMouseClicked
        
        Login_Activity login_Activity = new Login_Activity();
        login_Activity.setVisible(true);
        login_Activity.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_sentToLogin_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea adress_txt;
    private javax.swing.JPasswordField confpass_txt;
    private javax.swing.JRadioButton female_opt_btn;
    private javax.swing.JTextField fname_txt;
    private javax.swing.JButton imageSelect_btn;
    private javax.swing.JLabel image_path_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname_txt;
    private javax.swing.JRadioButton male_opt_btn;
    private javax.swing.JPasswordField pass_txt;
    private javax.swing.JTextField phone_txt;
    private javax.swing.JButton register_btn;
    private javax.swing.JLabel sentToLogin_btn;
    private javax.swing.JTextField uname_txt;
    // End of variables declaration//GEN-END:variables
}
